version: '3.8'
services:
  test_db:
    image: postgres:latest
    ports:
      - "5433:5432" # We use a different port (5433) to avoid conflicts!
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    restart: always